# Getting Started

## Aquatic Respirometry

There are four broad methodological approaches in aquatic respirometry: *closed-chamber*, *intermittent-flow*, *flow-through* and *open-tank*. 

In **closed-chamber** respirometry, $O_2$ decrease is measured within a hermetically sealed chamber of known volume, sometimes set within a closed loop to allow mixing of the environment within the chamber. Oxygen recordings may be continuous through use of an oxygen probe, periodic through withdrawing water or gas samples at set intervals, or a two-point measurement consisting of the initial and final concentrations. Metabolic rates are estimated from the $O_2$ timeseries by assuming a linear relationship between variables, and estimates of metabolic rate are straightforward in constant volume respirometry using the equation: $$VO_2 = \dot O_2V$$ where $\dot O_2$ is the slope of the regression that describes the rate of change in $O_2$ concentration over time, or in the case of a two-point measurement, the difference in $O_2$ concentration divided by time elapsed, and $V$ is the volume of fluid in the container (Lighton 2008).

In **intermittent-flow** respirometry, $O_2$ concentration is measured as described above, but periodically the chamber is flushed with new water or air, returning it to initial conditions, resealed, and the experiment repeated (Svendsen et al. 2016). This technique is essentially the same as closed respirometry, but with the ability to conduct replicates easily. Depending on the metabolic rate metric being investigated, final respiration rate can be calculated as the mean of the measures (e.g. Carey et al. 2016), or the lowest or highest rates recorded in any trial (e.g. Stoffels 2015).

**Flow-through** respirometry involves a closed chamber, but with a regulated flow of air or water through it at a precisely determined rate. After equilibrium has been achieved, the oxygen concentration differential between the incurrent and excurrent channels, along with the flow rate, allows calculation of the oxygen extracted from the flow volume per unit time: $$\dot{V}O_2 = (C_iO_2 - C_eO_2)FR$$ where $\dot{V}O_2$ is the rate of $O_2$ consumption over time, $C_iO_2$ and $C_eO_2$ are the incurrent and excurrent $O_2$ concentrations, and $FR$ is the flow rate through the system (Lighton 2008).

A final method is **open-tank** respirometry, in which a tank or semi-enclosed area open to the atmosphere is used, but the input or mixing rate of oxygen from the surroundings has been quantified or found to be negligible relative to oxygen consumption of the specimens (Leclercq et al. 1999). It is seldom used, but for some applications it is a sufficient and practical methodology (Gamble et al. 2014). The common equation used for open respirometry is: $$\dot{V}O_2 = \dot O_2V + \phi_d$$ where $\dot O_2V$ is the slope of the regression that relates $O_2$ concentration to time, $V$ is the volume of the arena and $\phi_d$ is the oxygen flux as determined by Fick's Law (Leclercq et al. 1999).

## The `respR` R package

`respR` is a package designed to process the data from all of these types of respirometry experiment. It is designed primarily for aquatic respirometry, although because many of the main functions are unitless it is adaptable for use with gaseous respirometry, and indeed analysis of other data where a parameter may change over time. 

When working with respirometry data, you will often need to:

1. Ensure that the data, or at least a **subset** of the data, is representative of the research question of interest.
2. Perform an initial analysis of the data to **estimate** the rate of change in oxygen concentration or amount.
3. Depending on the experimental setup, **correct** for background usage of oxygen by micro-organisms, or correct for oxygen flux from the air.
4. **Convert** the resulting usage rate to the volumetric and mass-specific rates in the appropriate units.

The `respR` package allows determination of common respirometry metrics and contains several functions to make this process straightforward.

- It provides visual feedback and diagnostic plots to help you explore, subset and analyse your data.
- It uses computational techniques such as *rolling regressions* and *kernel density estimates* to determine **maximum**, **minimum** or **most linear** rates within time-series data.
- The package takes an object-oriented approach, with all functions outputting objects which can be read by subsequent functions.
- By separating the workflow into a series of connected functions, you can "mix and match" functions to help you achieve your result.
- Output objects can also be saved or exported, and contain all raw data, parameters used in calculations, and results, allowing for a fully documented and reproducibile analysis of respirometry data.

## Example Data

We have provided example data that can be used immediately once `respR` is loaded (`urchins.rd()`, `intermittent.rd()`, `zeb_intermittent.rd()`, `sardine.rd()`, `squid.rd()`,  `flowthrough.rd()`). 

```{r, echo=TRUE}
data(package = "respR")
```